# Generated by Django 4.1.3 on 2022-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takeinput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
