# Generated by Django 4.1.3 on 2022-11-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedata',
            fields=[
                ('Srno', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Coursename', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Takeinput',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.courses'),
        ),
    ]
