# Generated by Django 4.1.3 on 2022-11-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_coursedata_courses_delete_takeinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
